### ISSUE TITLE
cmap iter with erase_at visits element twice

### ISSUE THREAD

**Issue by camel-cdr** [stclib/STC#54]
I've been fuzzing my own hash table implementation inspired by STCs cmap, and found this unexpected behavior.
STC seems to have the same problem, here is the code to reproduce it:

```c
#define i_key uint8_t
#define i_val uint8_t
#define i_tag name
#include "STC/include/stc/cmap.h"

int
main(void)
{
	cmap_name map = cmap_name_init();
	cmap_name_insert(&map, 1, 0);
	cmap_name_insert(&map, 70, 35);

	size_t count = 0;
	for (cmap_name_iter it = cmap_name_begin(&map); it.ref; ) {
		if (it.ref->second % 2 == 0)
			it = cmap_name_erase_at(&map, it);
		else
			cmap_name_next(&it);
		++count;
	}

	printf("count: %zu (expected 2)\n", count); // count is 3 run
}
```

The problem occurs when two values are inserted into the last bucket:
even inserted to end
odd inserted to end, moved to start

the iteration now looks like this:
```
      | del e, mov o back to end
o000e | o000e | 0000o
^           ^       ^
1.          2.      3.
```

notice that we visit "o" twice.

I don't think this is fixable using backshift deletion, but I think this behavior should be documented.

**Comment by camel-cdr** [comment]
https://github.com/stclib/STC/blob/0516aa3ae823ed9a22b2c5f776948c8447c32c31/docs/cmap_api.md?plain=1#L12-L13

This seems wrong, since the order of elements can change when erasing.

**Comment by tylov** [comment]
Ah. didn't think of that. Yes, it can't really be fixed without using tombstones instead of back shifting. As you say, fixing the documentation may be OK. When iterating while removing, it means you may visit elements twice, which is what the documentation should state. This is still a viable and efficient way to remove elements which matches a predicate, even though you may have to reject some elements twice.

**Comment by tylov** [comment]
closed as won't fix.
